# Config for OFStackableSpawners

messages:
  spawnerPlaced: "&aSpawner placed!"
  spawnerStacked: "&aSpawner stacked!"
  spawnerRemoved: "&aSpawner removed!"
  abandonedSpawnerRemoved: "&aAbandoned spawner removed!"
  oneSpawnerStackRemoved: "&aOne spawner stack is removed!"
  xpTaken: "&a%amount%XP taken!"
  itemTaken: "&aItem(s) taken!"
  itemsSold: "&aAll spawner items are sold for total %worth%!"
  spawnerGiven: "&aSpawners given!"
  youReceivedSpawner: "&aA moderator gave spawner(s) to you!"

  error:
    unknownSpawnerType: "&4Unkown spawner type, can't be stacked or placed!"
    spawnerCantBeMoreStacked: "&4Spawner can't be stacked more!"
    abandonedSpawnersCantBeStacked: "&4Abondened spawners can't be stacked!"
    notEnoughItem: "&4Not enough item to take!"
    notEnoughXP: "&4Not enough xp to take!"
    abandonedSpawnersCantOpen: "&4Abandoned spawners can't be opened!"
    cantInteract: "&4Another player is displaying the inventory so you can't open!"
    noItemToSell: "&4The spawner has no sellable item!"
    notEnoughPlayTime: "&4You don't have enough play time in server! Required play time %time% minutes!"
    playerIsNotOnline: "&4Player isn't online!"

# Will be multiplied by stacked amount
xpGeneration: 10

# What's the min play time for (as minutes) break (any) spawner
minPlayTime: 360

# What's the generate rate for ALL spawners (as seconds)
generateDelay: 60

# Inventory config
inventory:
  mainMenu:
    mainMenuInventoryTitle: "&7Spawnmer menu"
    items:
      storageDisplayItem:
        type: CHEST
        name: "&aStorage inventory"
        lore:
          - "&aDo left click to open storage inventory"
          - "&aDo right click to sell all stored items"
        slot: 10

      stackDisplayItem:
        type: SPAWNER
        name: "&d%spawner_stack%x &b%spawner_type%"
        slot: 13

      xpDisplayItem:
        type: EXPERIENCE_BOTTLE
        name: "&aCollect %spawner_xp% XP"
        slot: 16

  storageMenu:
    storageMenuInventoryTitle: "&7Spawner storage"
    storageItemFormat:
      itemDisplayName: "Stored: &6%item_amount%/%max_item_amount% &9%item_type%"
      itemLore:
        - "&6Do left click to take 1x"
        - "&6Do right click to take 16x"